on:
  fork:
  push:
    branches: [ main ]
  issues:
    types: [ opened ]
  issue_comment:
    types: [ created ]
  pull_request_target:
    types: [ opened ]
  pull_request_review_comment:
    types: [ created ]

jobs:

  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1.1.1

        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: '<h1>It''s great having you contribute to this project</h1> Welcome to the community :nerd_face: :rocket: [Join Discord](https://discord.gg/vUHMxPvege) '
          pr-message: '<h1>It''s great having you contribute to this project</h1> Welcome to the community :nerd_face: [Join Discord](https://discord.gg/vUHMxPvege) '
          footer: 'If you would like to continue contributing to open source and would like to do it with an awesome inclusive community, you should join our <a href="https://discord.gg/vUHMxPvege">Discord</a> chat and our <a href="https://github.com/CodeForbit">GitHub Organisation</a> - we help and encourage each other to contribute to open source little and often 🤓 . Any questions let us know.'